# SPDX-License-Identifier: GPL-2.0
# Orange Pi 5 focused Rockchip RK3588S device tree configuration

# Orange Pi 5 basic model only
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588s-orangepi-5.dtb
dtb-$(CONFIG_ARCH_ROCKCHIP) += rk3588s-orangepi-5-ap6275p.dtbo